name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://endoflife.date/kubernetes
          - tag: latest
            version: stable
          - tag: "1.34"
            version: v1.34.0
          - tag: "1.33"
            version: v1.33.4
          - tag: "1.32"
            version: v1.32.8
          - tag: "1.31"
            version: v1.31.12
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        id: buildx
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/kubectl
          tags: |
            type=raw,value=${{ matrix.version }}
            type=raw,value=${{ matrix.tag }}
      - uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && matrix.version == 'stable') }}
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          build-args: VERSION=${{ matrix.version }}
